version: '3.1'

services:
    mysql:
        image: mysql:5.7
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: wordpressroot
            MYSQL_DATABASE: dockerwp
            MYSQL_USER: dockerwp_user
            MYSQL_PASSWORD: wordpress
        volumes:
            - ./db_data:/var/lib/mysql

    wordpress:
        image: wordpress:latest
        restart: always
        ports:
            - 80:80
        depends_on:
            - mysql
        environment:
            WORDPRESS_DB_HOST: mysql:3306
            WORDPRESS_DB_NAME: dockerwp
            WORDPRESS_DB_USER: dockerwp_user
            WORDPRESS_DB_PASSWORD: wordpress
        volumes:
            - ./wordpress/wp-content:/var/www/html/wp-content
            - ./wordpress/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
